### ISSUE TITLE
Create a YAML setup to import into K8s / OpenShift

### ISSUE THREAD

**Issue by DaleBingham** [Cingulara/openrmf-web#50]
OpenShift uses ` oc new-project xxxxxx ` so some manual steps may happen. And then the rest should be automated.

The links to the APIs may be a ConfigMap that embeds a .JS file into the web pod so we can point to where the services are for now. Eventually this is Linkerd/Gloo/Istio/Kong service mesh.

**Comment by Cingulara** [comment]
We are going to use k8s for the setup. OpenShift has to be updated for the Routes versus ingress, otherwise good to go. 

I have this working for everything BUT the WebUI that points to the /js/apis.js with all the paths to the APIs. I need to adjust this w/ a config map to get it going correctly and mapping right, then check CORS. Once that works later this week, this is done and on to AuthZ and AuthN.

**Comment by Cingulara** [comment]
added liveness probes and readiness probes to k8s. I need to document how k8s is setup and continue to enrich that. Right now it is still a bit of a 'pet' process to stand it up correctly, and then 'cattle' takes over w/ APIs and msg. I can do better with it for sure. Or someone else that wants to pick that part up.

**Comment by Cingulara** [comment]
Once documentation is done and k8s is ripped down, and tested from scratch this can be closed out and version 0.7 tagged and released. Then on to AuthN and AuthZ which is a big step.

**Comment by Cingulara** [comment]
updated the docs on how to use the hostname. It is not "scripted" in helm as of yet but works in k8s if you setup your DB's and messaging as 'pets' and then run your cattle :) hahah
